### ISSUE TITLE
[Merged] SO_REUSEPORT

### ISSUE THREAD

**Issue by LemonBoy** [flightaware/Tcl-bounties#1]

**Comment by bovine** [comment]
What is the reason for withdrawing this?

**Comment by LemonBoy** [comment]
Ad discussed on irc a TIP is needed, I do have a working and complete patch but haven't submitted a TIP proposal yet.

**Comment by bovine** [comment]
Keeping the issue here opened and referencing your work is probably still preferable so that others avoid duplicate work. You can also add the link to your TIP and any further updates as they are made, for tracking purposes.

**Comment by LemonBoy** [comment]
The TIP has been submitted, you can find it [here](http://www.tcl.tk/cgi-bin/tct/tip/456.html).

**Comment by LemonBoy** [comment]
For reference, all the work is being done in the [tip-456](http://core.tcl.tk/tcl/timeline?r=tip-456) branch

**Comment by nijtmans** [comment]
Waiting for FA feedback. Is the TIP/implementation according to expectation? If so, the TIP is ready for the TCT vote

**Comment by lehenbauer** [comment]
Hi.  It looks good to me.  I don't know when you would not want SO_REUSEADDR but I get putting it in there for completeness.  We are happy with the TIP for support of SO_REUSEPORT.  Thanks.

**Comment by LemonBoy** [comment]
As of today the `tip-456` branch is now part of trunk

**Comment by lehenbauer** [comment]
Awesome!

**Comment by nijtmans** [comment]
TIP vote has been done:  TIP is accepted for Tcl 8.7. See: [http://www.tcl.tk/cgi-bin/tct/tip/456]

**Comment by bovine** [comment]
Are there plans to backport this also to 8.6? That would be ideal.

**Comment by lehenbauer** [comment]
We have tested this and it works.

**Comment by LemonBoy** [comment]
Is there anything else to be done wrt this?

**Comment by bovine** [comment]
I'd still like to seeing an 8.6 with this... Has Tcl Core given an opinion on that possibility yet?

**Comment by LemonBoy** [comment]
I don't think a brand new feature is eligible for a backport even though the API has remained unchanged but, to answer your question, I haven't really asked the TCL core team yet, maybe @nijtmans can shed some light on the matter.

**Comment by bovine** [comment]
ok, marking closed. payment has been issued.

**Comment by LemonBoy** [comment]
I..I guess you need a way to send the money this way, no?

**Comment by resuna** [comment]
Send us your paypal account info. My email is in my profile.
