### ISSUE TITLE
Intent to implement the tclreadline enhancements

### ISSUE THREAD

**Issue by dbohdan** [flightaware/Tcl-bounties#16]
I'd like a clarification on one thing: the rules say that
>* For bounties under $10,000, the bounty will be paid when the code is accepted into the Tcl core, or if not part of the core, accepted by the package maintainer.

Since tclreadline isn't part of the core and isn't maintained (no releases since 2001; there is a [fork](https://chiselapp.com/user/aspect/repository/tclreadline/timeline) but its owner states you shouldn't expect it to be maintained), what will decide when the bounty is paid?

**Comment by lehenbauer** [comment]
Hi dbohdan,

OK, we've forked tclreadline from sourceforge to github.com/flightaware/tclreadline.  There's a master branch and a devel branch.  There are a few newer commits on the devel branch.

You fork the repo on github, figure out which branch is the best place to start from, go from there, then submit a pull request with your fixes and when we confirm that they're working, we'll merge the pull request and pay the bounty.

-karl

**Comment by dkfellows** [comment]
I think that tclreadline is unlikely to ever get accepted into Tcl itself due to license issues (damn GPL). A maintained library that works with `package require` (perhaps in one's `.tclshrc`) would be a reasonable alternative target.

**Comment by dbohdan** [comment]
@lehenbauer Thanks for pointing out you have a fork since I started working from a different version.

I've submitted my pull request here: https://github.com/flightaware/tclreadline/pull/1.

**Comment by lehenbauer** [comment]
This looks great.  We're testing now.  Will let you know shortly.

**Comment by lehenbauer** [comment]
We have tested your pull request and determined that you have fulfilled the conditions of the bounty.  We've emailed separately to arrange payment of the $2500 boundary.  Congratulations!

**Comment by dbohdan** [comment]
Awesome!
