### ISSUE TITLE
TIP #459: "Tcl package introspection improvements" completed

### ISSUE THREAD

**Issue by nijtmans** [flightaware/Tcl-bounties#17]
I like the "package files" proposal

**Comment by nijtmans** [comment]
Waiting for FA feedback. Is the TIP/implementation according to expectation? If so, the TIP is ready for the TCT vote

**Comment by lehenbauer** [comment]
This is exactly what we are looking for.

**Comment by nijtmans** [comment]
Full implementation is now on trunk.

TIP voting has been done as well.

Please test if this really fulfils your requirements.

**Comment by resuna** [comment]
Looks good to me. @lehenbauer ?

Aside: Any way to find out what the pkgIndex.tcl file a package was defined in was, or does that happen at too high a level?

(note, not a requirement)

**Comment by nijtmans** [comment]
Answer:    Even though the name of the pkgIndex file is available earlier, it is very well possible to remember it and store it together with the other files. This commit does exactly that:        http://core.tcl.tk/tcl/info/a5e03581131f6003   Please test this, if OK I'll merge it to trunk.

**Comment by resuna** [comment]
Looks good!

**Comment by resuna** [comment]
One minor inconsistency I notice is that "info loaded" makes the name optional, and "package files" doesn't.

**Comment by nijtmans** [comment]
If you want information on all available packages you can do:

**Comment by nijtmans** [comment]
foreach x [package names] {puts stdout "$x : [package files $x]"}

**Comment by resuna** [comment]
Fair enough, and not a requirement, it just tickled my OCD.

**Comment by resuna** [comment]
If you can merge that last change into trunk and send me your preferred email address we'll close this one out!

**Comment by nijtmans** [comment]
Last change now merge to trunk. My email can be found in the TIP header: [http://www.tcl.tk/cgi-bin/tct/tip/459]

**Comment by nijtmans** [comment]
Everything completed, payment received. So this issue can be closed. Thanks!
