### ISSUE TITLE
NaviServer - TCL - Virtual ips for single IP multidomain hosting

### ISSUE THREAD

**Issue by JonLittleIT** [flightaware/Tcl-bounties#29]
I have been working with navi web server and there have been issues because we cant change the settings so you can only need 1 public IP and serve multiple sites on a single web server.

**Comment by dbohdan** [comment]
Is this a new bounty?

**Comment by resuna** [comment]
I think it's a misplaced issue. It should probably have been posted to https://bitbucket.org/naviserver/naviserver/

**Comment by JonLittleIT** [comment]
I wanted to see if this is possible or if its a feature request. I am new to Navi and dont see this in any documentation.

**Comment by resuna** [comment]
NaviServer's primary development seems to be at the bitbucket site I linked to in the previous message. You need to bring up your issues there, we have nothing to do with it - even as a user - that I am aware of.
