### ISSUE TITLE
TCL BUG... matching curly parentheses when code is commented out and reporting fail error in code. 

### ISSUE THREAD

**Issue by wm2015email** [flightaware/Tcl-bounties#38]
I just found a bug in the TCL interpreter...  When you have an unbalanced parantheses in commented out code ... it still reports it as an error.  Example:

```
PS C:\bb\fpga\top\run> wsl

$ tclsh tmp.tcl
wrong # args: should be "proc name args body"
    while executing
"proc dfsdf {args} {
#       # Instantiate + Generate all + Synthesize Core
#       if ($level == 3} {
#               return
#   }"
    (file "tmp.tcl" line 1)
$
```
Notice that I used the wrong parenthesis for beginning "if statement" using "(" instead of "{"...  however, when I source this tcl code, it reports an error even when the code that causes the erroris commented out...

[tmp.txt](https://github.com/flightaware/Tcl-bounties/files/4746572/tmp.txt)

**Comment by sebres** [comment]
Firstly. this is not a BUG but feature. This is how tcl-parsing (JIT interpolation or substitution) works.
Read the documentation [Summary of Tcl language syntax](https://www.tcl-lang.org/man/tcl/TclCmd/Tcl.htm) or a wiki page
[Why can I not place unmatched braces in Tcl comments](https://wiki.tcl-lang.org/page/Why+can+I+not+place+unmatched+braces+in+Tcl+comments).

And last but not least, this is basically a wrong repository for issues like that (this repository is quasi a bounties collection of Flightaware for the Tcl language).
Bugs for Tcl must be opened as [ticket in Tcl-Repository](https://core.tcl-lang.org/tcl/tktnew).

Thus it can be closed.

**Comment by resuna** [comment]
In addition to Sergey's comments, the Bug Bounty program is on hold due to the world situation.

**Comment by resuna** [comment]
Check out the Tcl mailing lists at https://www.tcl-lang.org/
