### ISSUE TITLE
Dibs on Scotty

### ISSUE THREAD

**Issue by eviltwinskippy** [flightaware/Tcl-bounties#7]
I'm working on using the new toys in an upcoming release of TEA to re-do the entire build process for Scotty

**Comment by bovine** [comment]
For reference, FlightAware has a fork of Scotty here: https://github.com/flightaware/scotty  (I believe our fork was taken from some other obsolete source?)

But it appears that someone else has a 2015 fork on SourceForge, which may have possibly been based off of ours, but may now be abandoned again?  https://sourceforge.net/p/tkined-scotty/code/HEAD/tree/  It appears to possibly have some Linux porting fixes that could be useful to incorporate.

It would be nice to figure out the official hosting situation and update http://wiki.tcl.tk/691

**Comment by eviltwinskippy** [comment]
I’ll check into that. Thanks for the heads up!

—Sean

**Comment by jorge-leon** [comment]
Hello,

how is your progress on this?

**Comment by eviltwinskippy** [comment]
Congradulations jorge-leon. Thanks for getting that nailed down.
